hide_download: true
hide_download_original: null
leftnav:
- identifier: 51b6cef9-60b0-f4d3-a8e5-3d828a48c89f
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: b4775d4e-7ae4-ba2e-3c88-3ddde89749ba
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: eab642f0-ded5-10fd-e72b-0d18ce30e840
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: bb5c14b6-21d6-3ea0-1a9b-601e2b84c421
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 40
- identifier: ab0f0114-9754-91bd-85f0-33115845cf86
  name: Projects
  pageRef: /pages/projects
  weight: 50
